### ISSUE TITLE
Outdated Packages - Failing to build

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/starwars-spaceships#8]
This project is failing to build due to some outdated packages:

- NPM

- React-Scripts

I have updated both of these packages and it is still failing to build.

Please see the following Travis error log for further information on why this build is failing:
https://travis-ci.org/zero-to-mastery/starwars-spaceships/builds/388644685?utm_source=github_status&utm_medium=notification

**Comment by Josh-Broomfield** [comment]
You've got node version 10 installed, which isn't listed in a supported versions for npm. I've got 8.11.4 installed.
